---
components:
  schemas:
    GetSentinelCommand:
      x-ngsi:
        uri-prefix: "https://raw.githubusercontent.com/H2020-MEDIATE/Mediate_Data_Model_Public/main/OM2getSentinelCommand/schema.json"

      description: >-
        Schema for Service Manager registry retrieval command OM2. This command
        is sent by the Orchestrator to the Service Manager to request the full
        representation of a specific Sentinel and its associated Assets.
      type: object

      required:
        - id
        - type
        - timestamp

      properties:
        id:
          anyOf:
            - description: Property. Identifier format of any NGSI entity.
              maxLength: 256
              minLength: 1
              pattern: '^[\w\-\.\{\}\$\+\*\[\]`|~^@!,:\\]+$'
              type: string
          format: uri
          type: string
          description: Unique identifier of this Get Sentinel command.
          x-ngsi:
            type: Property


        type:
          type: string
          enum:
            - getSentinelCommand
          description: NGSI-LD entity type. It has to be getSentinelCommand.
          x-ngsi:
            type: Property

        originator:
          type: string
          enum:
            - ORCHESTRATOR
          description: Component that generated the command.
          x-ngsi:
            type: Property

        messageId:
          type: string
          description: Unique identifier of this command message.
          x-ngsi:
            type: Property

        correlationId:
          type: string
          description: >-
            Identifier used to correlate this command with the corresponding
            SentinelResponseEvent.
          x-ngsi:
            type: Property

        timestamp:
          type: string
          format: date-time
          description: Date and time at which the command was generated.
          x-ngsi:
            type: Property

        sentinelId:
          anyOf:
            - description: Property. Identifier format of any NGSI entity.
              maxLength: 256
              minLength: 1
              pattern: '^[\w\-\.\{\}\$\+\*\[\]`|~^@!,:\\]+$'
              type: string
          format: uri
          type: string
          description: Sentinel entity requested by the Orchestrator.
          x-ngsi:
            type: Relationship

info:
  title: MEDIATE OM2 Get Sentinel Command
  version: "0.1.0"
  description: >-
    Data model for registry retrieval command OM2, used by the Orchestrator to
    request the full representation of a specific Sentinel from the Service
    Manager.

openapi: "3.0.3"

paths:
  /ngsi-ld/v1/entities:
    get:
      responses:
        "200":
          description: OK
          content:
            application/ld+json:
              schema:
                type: object
