---
components:
  schemas:
    GetAssetCommand:
      x-ngsi:
        uri-prefix: "https://raw.githubusercontent.com/H2020-MEDIATE/Mediate_Data_Model_Public/main/OM3getAssetCommand/schema.json"

      description: >-
        Schema for Service Manager registry retrieval command OM3. This command
        is sent by the Orchestrator to the Service Manager to request the full
        representation of a specific Asset.
      type: object

      id:
        anyOf:
          - description: Property. Identifier format of any NGSI entity.
            maxLength: 256
            minLength: 1
            pattern: '^[\w\-\.\{\}\$\+\*\[\]`|~^@!,:\\]+$'
            type: string
        format: uri
        type: string
        description: Unique identifier of this Get Asset command.
        x-ngsi:
          type: Property

      required:
        - id
        - type
        - timestamp

      properties:
        type:
          type: string
          enum:
            - getAssetCommand
          description: NGSI-LD entity type. It has to be getAssetCommand.
          x-ngsi:
            type: Property

        originator:
          type: string
          enum:
            - ORCHESTRATOR
          description: Component that generated the command.
          x-ngsi:
            type: Property

        messageId:
          type: string
          description: Unique identifier of this command message.
          x-ngsi:
            type: Property

        correlationId:
          type: string
          description: >-
            Identifier used to correlate this command with the corresponding
            AssetResponseEvent.
          x-ngsi:
            type: Property

        timestamp:
          type: string
          format: date-time
          description: Date and time at which the command was generated.
          x-ngsi:
            type: Property

        assetId:
          anyOf:
            - description: Property. Identifier format of any NGSI entity.
              maxLength: 256
              minLength: 1
              pattern: '^[\w\-\.\{\}\$\+\*\[\]`|~^@!,:\\]+$'
              type: string
          format: uri
          type: string
          description: Asset entity requested by the Orchestrator.
          x-ngsi:
            type: Relationship

info:
  title: MEDIATE OM3 Get Asset Command
  version: "0.1.0"
  description: >-
    Data model for registry retrieval command OM3, used by the Orchestrator to
    request the full representation of a specific Asset from the Service
    Manager.

openapi: "3.0.3"

paths:
  /ngsi-ld/v1/entities:
    get:
      responses:
        "200":
          description: OK
          content:
            application/ld+json:
              schema:
                type: object
